schema_version: 1

context:
  name: azure-multiapi-storage
  version: 1.4.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/azure-multiapi-storage-${{ version }}.tar.gz
  sha256: 45f15dfb5c4bda8b9627734b5cc72c45f436d796e2e216be88239c6178cd0f71

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - setuptools
    - python ${{ python_min }}.*
    - pip
  run:
    - python >=${{ python_min }}
    - azure-common
    - python-dateutil
    - requests
    - azure-core >=1.10.0,<2.0.0
    - msrest >=0.6.18
    - cryptography >=2.1.4

tests:
  - python:
      imports:
        - azure
      pip_check: true
      python_version: ${{ python_min }}.*
about:
  summary: Microsoft Azure Storage Client Library for Python with multi API version support.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/Azure/azure-multiapi-storage-python

extra:
  recipe-maintainers:
    - janjagusch
